algo_digitado = input('Digite algo: ')
print(type(algo_digitado))
print(f'"{algo_digitado}" é alfa numérico? {algo_digitado.isalnum()}')
print(f'"{algo_digitado}" é numérico? {algo_digitado.isnumeric()}')
print(f'"{algo_digitado}" é uma letra? {algo_digitado.isalpha()}')
print(f'"{algo_digitado}" pertence a tabela ASCII? {algo_digitado.isascii()}')
print(f'"{algo_digitado}" é decimal? {algo_digitado.isdecimal()}')
print(f'"{algo_digitado}" é dígito? {algo_digitado.isdigit()}')
print(f'"{algo_digitado}" é minúsculo? {algo_digitado.islower()}')
print(f'"{algo_digitado}" é maiúsculo? {algo_digitado.isupper()}')
print(f'"{algo_digitado}" est? {algo_digitado.isalnum()}')